version: '3.8'

services:
  # Redis for message queuing and caching
  redis:
    image: redis:7-alpine
    container_name: skippy-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # PostgreSQL for persistent data
  postgres:
    image: postgres:15-alpine
    container_name: skippy-db
    environment:
      POSTGRES_DB: skippy
      POSTGRES_USER: skippy
      POSTGRES_PASSWORD: skippy_secure_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  # n8n Orchestration Hub
  n8n:
    image: n8nio/n8n:latest
    container_name: skippy-n8n
    ports:
      - "192.168.0.229:5678:5678"
      - "192.168.0.229:8123:8123"
    environment:
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=skippy_admin
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_DATABASE=skippy
      - DB_POSTGRESDB_USER=skippy
      - DB_POSTGRESDB_PASSWORD=skippy_secure_password
      - N8N_ENCRYPTION_KEY=your_encryption_key_here
      - WEBHOOK_URL=http://192.168.0.229:5678/
    volumes:
      - n8n_data:/home/node/.n8n
      - ./n8n/custom:/home/node/.n8n/custom
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

volumes:
  redis_data:
  postgres_data:
  n8n_data: